---
title: "Case classification analysis"
author: Raphael Saldanha
date: last-modified
---

This is a descriptive report about dengue case classification and criteria.

## Packages

```{r}
#| message: false
library(tidyverse)
library(arrow)
library(knitr)
library(lubridate)
source("../functions.R")
```

### Execution node

```{r}
node_name()
```

## Load data

```{r}
important_vars <- c("DT_SIN_PRI", "RESUL_SORO", "SOROTIPO", "CLASSI_FIN", "CRITERIO")

valid_interval <- interval(ymd("2011-01-01"), ymd("2022-12-31"))

dengue_files_list <- c(
  data_dir("dengue_data/parquets/dengue_2016.parquet"),
  data_dir("dengue_data/parquets/dengue_2017.parquet"),
  data_dir("dengue_data/parquets/dengue_2018.parquet"),
  data_dir("dengue_data/parquets/dengue_2019.parquet"),
  data_dir("dengue_data/parquets/dengue_2020.parquet"),
  data_dir("dengue_data/parquets/dengue_2021.parquet"),
  data_dir("dengue_data/parquets/dengue_2022.parquet")
)

dengue <- open_dataset(sources = dengue_files_list) %>%
  select(all_of(important_vars)) %>%
  collect() %>%
  mutate(DT_SIN_PRI = ymd(DT_SIN_PRI)) %>%
  filter(DT_SIN_PRI %within% valid_interval) %>%
  filter(CLASSI_FIN != "6")
```

## Final classification and criteria

```{r}
dengue %>%
  group_by(CLASSI_FIN, CRITERIO) %>%
  summarise(freq = n()) %>%
  ungroup() %>%
  kable(
    format.args = list(big.mark = ".", decimal.mark = ",")
  )
```

```{r}
dengue_classifications <- c("Febre hemorrágica do dengue", "Síndrome do choque do dengue", "Dengue com sinais de alarme",
  "Dengue clássico", "Dengue com complicações", "Dengue",
  "Dengue grave")
```

```{r}
dengue_cases_classification <- dengue %>% 
  mutate(CLASSI_FIN = case_when(
    CLASSI_FIN %in% dengue_classifications ~ "Confirmed",
    CLASSI_FIN == "Descartado" ~ "Discarded",
    CLASSI_FIN == "Inconclusivo" ~ "Inconclusive",
    CLASSI_FIN == 6 ~ "Invalid",
    is.na(CLASSI_FIN) ~ "Missing",
    .default = CLASSI_FIN
  )) %>%
  mutate(DT_SIN_PRI = lubridate::ceiling_date(x = DT_SIN_PRI, unit = "month")) %>%
  group_by(DT_SIN_PRI, CLASSI_FIN) %>%
  summarise(freq = n()) %>%
  ungroup() 
```

```{r}
write_parquet(x = dengue_cases_classification, sink = data_dir("dengue_data/parquet_classification/dengue_cases_classification.parquet"))
```

```{r}
ggplot(data =  dengue_cases_classification, aes(x = DT_SIN_PRI, weight = freq, fill = CLASSI_FIN)) +
  geom_bar() +
  scale_fill_hue(direction = 1) +
  scale_y_continuous(labels = scales::comma) +
  labs(fill = "Classificação") +
  theme_minimal() +
  theme(legend.position = "bottom") +
  labs(x = "Month of first symptom's onset", y = "Records", fill = "Classification")

ggsave(filename = "dengue_cases_classification.pdf")
```

## Sorological examination

```{r}
dengue %>%
  filter(CLASSI_FIN %in% dengue_classifications) %>%
  group_by(SOROTIPO) %>%
  summarise(freq = n()) %>%
  ungroup()
```

## Session info

```{r}
sessionInfo()
```
