---
title: "Raw files, chikungunya"
author: Raphael Saldanha
date: last-modified
---

This notebook presents the process of downloading SINAN Dengue raw data files from DataSUS, pre-processing steps using the `{microdatasus}` package and exporting the raw files to `parquet` files.

## Packages

```{r}
#| message: false
library(tidyverse)
# remotes::install_github("rfsaldanha/microdatasus")
library(microdatasus)
library(arrow)
source("../functions.R")
```

### Execution node

```{r}
node_name()
```

## Data download

```{r}
# for(a in 2016:2021){
#   tmp <- fetch_datasus(
#     year_start = a, year_end = a,
#     information_system = "SINAN-ZIKA"
#   )
# 
#   write_parquet(x = tmp, sink = paste0(data_dir("zika_data/parquets_raw/raw_zika_"),a, ".parquet"))
# 
#   tmp <- process_sinan_zika(data = tmp)
# 
#   write_parquet(x = tmp, sink = paste0(data_dir("zika_data/parquets/zika_"), a, ".parquet"))
# 
#   rm(tmp)
# }
```

::: callout-warning
This code chunk is commented to avoid unnecessary download again the raw DBC files from DataSUS.
:::

## Overview

```{r}
dengue <- open_dataset(sources = data_dir("dengue_data/parquets"))
```

```{r}
dengue %>% glimpse()
```

## Session info

```{r}
sessionInfo()
```
