project:
  type: website
  output-dir: docs/
  
execute: 
  freeze: auto

website:
  title: "Dengue AI"
  page-navigation: true
  back-to-top-navigation: true
  google-analytics: "G-ZMP18L536K"
  page-footer: 
    left: "Website made with [Quarto](https://quarto.org/), by Raphael Saldanha."
    right: "Inria | LNCC | PCDaS"
  navbar:
    background: primary
    search: true
    tools:
      - icon: github
        href: https://github.com/rfsaldanha/dengue
    left:
      - text: "Home"
        file: index.qmd
      - text: "Data"
        file: dengue_data.qmd
      - text: "Cluster analysis"
        file: cluster_analysis.qmd
      - text: "Modeling"
        file: dengue_model.qmd
      - text: "Software"
        file: software.qmd
      - text: "Publications"
        file: publications.qmd
      - text: "Exported data"
        file: export-data/exported_data.qmd  
      - text: "Presentations"
        file: presentations.qmd

  
  sidebar:
      collapse-level: 1
      contents: 
        - section: "Data"
          contents: 
            - section: "Dengue data"
              contents: 
                - dengue_data.qmd
                - dengue-data/raw_files.qmd
                - dengue-data/case_classification.qmd
                - dengue-data/missing_data.qmd
                - dengue-data/imputation.qmd
                - dengue-data/aggregated_database.qmd
            - weather_data.qmd
            - socioeconomic-data/socioeconomic_data.qmd
        - section: "Cluster analysis"
          contents: 
              - cluster_analysis.qmd
              - section: "Long time series"
                contents: 
                    - dengue-cluster/cluster_long.qmd
                    - dengue-cluster/cluster_long_scaled.qmd
              - section: "Municipality/year time series"
                contents:
                    - dengue-cluster/cluster_mun_year.qmd
                    - dengue-cluster/cluster_mun_year_cumulative.qmd
                    - dengue-cluster/cluster_mun_year_epi_year.qmd
        - section: "Modeling"
          contents: 
              - dengue_model.qmd
              - section: "Denque and weather lags"
                contents: 
                    - dengue-model/dengue_weather_lag_class.qmd
                    - dengue-model/dengue_weather_lag_reg.qmd
              - dengue-model/dengue_classification_symptoms_conditions_multi.qmd
              - section: "Dengue time series modelling"
                contents:
                    - dengue-model/dengue_ts_overview.qmd
                    - dengue-model/dengue_ts_data.qmd
                    - dengue-model/dengue_ts_global_model.qmd
              
        - software.qmd
        - publications.qmd
        - export-data/exported_data.qmd  
        - section: "Presentations"
          contents: 
              - presentations.qmd
              - presentations/presentation_test.qmd
        - publications.qmd

  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

published-title: "Last run"
date-format: "MMMM D, YYYY | HH:mm:ss Z"
