project:
  type: website
  output-dir: docs/
  
execute: 
  freeze: auto

website:
  title: "Dengue AI"
  page-navigation: true
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - text: "Dengue data"
        file: dengue_data.qmd
      - text: "Weather data"
        file: weather_data.qmd
      - text: "Cluster analyses"
        file: cluster_analysis.qmd
      - text: "Software"
        file: software.qmd
      - text: "Presentations"
        file: presentations.qmd
  
  sidebar:
      collapse-level: 1
      contents: 
        - section: "Dengue data"
          contents: 
            - dengue_data.qmd
            - dengue-data/raw_files.qmd
            - dengue-data/missing_data.qmd
            - dengue-data/imputation.qmd
            - dengue-data/aggregated_database.qmd
        - weather_data.qmd
        - section: "Cluster analysis"
          contents: 
              - cluster_analysis.qmd
              - dengue-data/raw_files.qmd
              - dengue-data/missing_data.qmd
              - dengue-data/imputation.qmd
              - dengue-data/aggregated_database.qmd
        - software.qmd
        - section: "Presentations"
          contents: 
              - presentations.qmd
              - presentations/presentation_test.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

published-title: "Last run"
