project:
  type: website
  output-dir: docs/
  
execute: 
  freeze: auto

website:
  title: "Dengue AI"
  navbar:
    background: primary
    search: true
    left:
      - text: "Home"
        file: index.qmd
      - sidebar:data
      - sidebar:cluster
      - about.qmd
  
  sidebar: 
    - id: data
      title: "Data"
      style: docked
      background: light
      collapse-level: 2
      contents: 
        - dengue-data/raw_files.qmd
        - dengue-data/missing_data.qmd
        - dengue-data/imputation.qmd
        - dengue-data/aggregated_database.qmd

    - id: cluster
      title: "Cluster"
      style: docked
      background: light
      collapse-level: 2
      contents: 
        - dengue-cluster/cluster_long.qmd
        - dengue-cluster/cluster_long_scaled.qmd
  
format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

published-title: "Last run"
