---
title: "Dengue and weather lags, regression task"
author: Raphael Saldanha
date: now
---

## Packages

```{r}
library(tidyverse)
library(tidymodels)
library(arrow)
library(timetk)
library(rpart.plot)
library(vip)
```

## Dengue data

### Subset and aggregate

Rio de Janeiro, RJ, aggregated by month.

```{r}
dengue_rj <- open_dataset("../dengue-data/parquet_aggregated/dengue_md.parquet") %>%
  filter(mun == 330455) %>%
  collect() %>%
  summarise_by_time(.date_var = date, .by = "month", freq = sum(freq, na.rm = TRUE))
```

```{r}
plot_time_series(.data = dengue_rj, .date_var = date, .value = freq, .smooth = FALSE, .title = "Dengue, absolute number of cases")
```

## Weather data

```{r}
tmax <- open_dataset(sources = "../weather-data/parquet/brdwgd/tmax.parquet") %>%
  filter(code_muni == 3304557) %>%
  filter(name == "Tmax_mean") %>%
  select(date, value) %>%
  collect() %>%
  filter(date >= min(dengue_rj$date) & date <= max(dengue_rj$date)) %>%
  summarise_by_time(.date_var = date, .by = "month", value = mean(value, na.rm = TRUE)) %>%
  rename(tmax = value)

prec <- open_dataset(sources = "../weather-data/parquet/brdwgd/pr.parquet") %>%
  filter(code_muni == 3304557) %>%
  filter(name == "pr_sum") %>%
  select(date, value) %>%
  collect() %>%
  filter(date >= min(dengue_rj$date) & date <= max(dengue_rj$date)) %>%
  summarise_by_time(.date_var = date, .by = "month", value = sum(value, na.rm = TRUE)) %>%
  rename(prec = value)

prec_avg <- open_dataset(sources = "../weather-data/parquet/brdwgd/pr.parquet") %>%
  filter(code_muni == 3304557) %>%
  filter(name == "pr_mean") %>%
  select(date, value) %>%
  collect() %>%
  filter(date >= min(dengue_rj$date) & date <= max(dengue_rj$date)) %>%
  summarise_by_time(.date_var = date, .by = "month", value = mean(value, na.rm = TRUE)) %>%
  rename(prec_avg = value)

rh <- open_dataset(sources = "../weather-data/parquet/brdwgd/rh.parquet") %>%
  filter(code_muni == 3304557) %>%
  filter(name == "RH_mean") %>%
  select(date, value) %>%
  collect() %>%
  filter(date >= min(dengue_rj$date) & date <= max(dengue_rj$date)) %>%
  summarise_by_time(.date_var = date, .by = "month", value = mean(value, na.rm = TRUE)) %>%
  rename(rh = value)

wind <- open_dataset(sources = "../weather-data/parquet/brdwgd/u2.parquet") %>%
  filter(code_muni == 3304557) %>%
  filter(name == "u2_mean") %>%
  select(date, value) %>%
  collect() %>%
  filter(date >= min(dengue_rj$date) & date <= max(dengue_rj$date)) %>%
  summarise_by_time(.date_var = date, .by = "month", value = mean(value, na.rm = TRUE)) %>%
  rename(wind = value)
```

```{r}
plot_time_series(.data = tmax, .date_var = date, .value = tmax, .smooth = FALSE, .title = "Max temp, average")
```

```{r}
plot_time_series(.data = prec, .date_var = date, .value = prec, .smooth = FALSE, .title = "Precipitation, sum")
```

```{r}
plot_time_series(.data = prec_avg, .date_var = date, .value = prec_avg, .smooth = FALSE, .title = "Precipitation, average")
```

```{r}
plot_time_series(.data = rh, .date_var = date, .value = rh, .smooth = FALSE, .title = "Relative humidity, average")
```

```{r}
plot_time_series(.data = wind, .date_var = date, .value = wind, .smooth = FALSE, .title = "Wind, average")
```

## Join data

```{r}
res <- inner_join(x = dengue_rj, y = tmax, by = "date") %>%
  inner_join(prec, by = "date") %>%
  inner_join(prec_avg, by = "date") %>%
  inner_join(rh, by = "date") %>%
  inner_join(wind, by = "date") %>%
  select(date, cases = freq, tmax, prec, rh, wind)
```

## Decision tree

### Prepare data

-   Remove date

-   Lag variables: 6 months

```{r}
res_prep <- res %>%
  select(-date) %>%
  tk_augment_lags(.value = c(tmax, prec, wind, rh), .lags = 1:6)
```

### Parameters

```{r}
tree_spec <- decision_tree() %>%
  set_engine("rpart") %>%
  set_mode("regression")
```

## Fit model

```{r}
fit1 <- tree_spec %>%
  fit(cases ~ ., data = res_prep)
```

```{r}
fit1 %>% extract_fit_engine() %>%
  rpart.plot(roundint = FALSE)
```

```{r}
augment(fit1, new_data = res_prep) %>%
    mae(truth = cases, estimate = .pred)
```

```{r}
augment(fit1, new_data = res_prep) %>%
  select(cases, .pred) %>%
  mutate(t = row_number()) %>%
  pivot_longer(cols = c("cases", ".pred")) %>%
  ggplot(aes(x = t, y = value, color = name)) +
  geom_line() +
  theme_bw()
```

```{r}
fit1 %>% 
  extract_fit_engine() %>% 
  vip()
```
