---
title: "Raw cases"
author: Raphael Saldanha
date: last-modified
---

This notebook aims to cluster the Brazilian municipalities considering dengue raw cases time-series similarities.

## Packages

```{r}
#| message: false
library(tidyverse)
library(lubridate)
library(arrow)
library(timetk)
library(dtwclust)
library(kableExtra)
library(tictoc)
source("../functions.R")
```

## Load data

Load the bundled data.

```{r}
tdengue <- open_dataset(sources = data_dir("bundled_data/tdengue.parquet")) %>%
    select(mun, date, cases = cases_raw) %>%
    collect()

dim(tdengue)
```

### Prepare data

The chunk bellow formats the dataset for `tsclust` use.

```{r}
tdengue <- tdengue %>%
  # Prepare time series
  arrange(mun) %>%
  pivot_wider(names_from = mun, values_from = cases) %>%
  select(-date) %>%
  t() %>%
  # Convert object
  tslist()
```

```{r}
length(tdengue)
```

## Clustering

Sequence of `k` groups to be used.

```{r}
k_seq <- 2:10
```

### DTW (basic)

```{r}
tic()
clust_dtw <- tsclust(
  series = tdengue, 
  type = "partitional", 
  k = k_seq,
  distance = "dtw_basic",
  seed = 13
)
toc()
```

```{r}
names(clust_dtw) <- paste0("k_", k_seq)
res_cvi <- sapply(clust_dtw, cvi, type = "internal") %>% 
  t() %>%
  as_tibble(rownames = "k") %>%
  arrange(-Sil)

res_cvi %>%
  gt::gt()
```

```{r}
sel_clust <- clust_dtw[[res_cvi[[1,1]]]]

plot(sel_clust)
plot(sel_clust, type = "centroids", lty = 1)
```

```{r}
table(sel_clust@cluster)
```

### Soft-DTW

```{r}
tic()
clust_sdtw <- tsclust(
  series = tdengue, 
  type = "partitional", 
  k = k_seq,
  distance = "sdtw",
  seed = 13
)
toc()
```

```{r}
names(clust_sdtw) <- paste0("k_", k_seq)
res_cvi <- sapply(clust_sdtw, cvi, type = "internal") %>% 
  t() %>%
  as_tibble(rownames = "k") %>%
  arrange(-Sil)

res_cvi %>%
  gt::gt()
```

```{r}
sel_clust <- clust_sdtw[[res_cvi[[1,1]]]]

plot(sel_clust)
plot(sel_clust, type = "centroids", lty = 1)
```

```{r}
table(sel_clust@cluster)
```

### SBD

```{r}
tic()
clust_sbd <- tsclust(
  series = tdengue, 
  type = "partitional", 
  k = k_seq,
  distance = "sbd",
  seed = 13
)
toc()
```

```{r}
names(clust_sbd) <- paste0("k_", k_seq)
res_cvi <- sapply(clust_sbd, cvi, type = "internal") %>% 
  t() %>%
  as_tibble(rownames = "k") %>%
  arrange(-Sil)

res_cvi %>%
  gt::gt()
```

```{r}
sel_clust <- clust_sbd[[res_cvi[[1,1]]]]

plot(sel_clust)
plot(sel_clust, type = "centroids", lty = 1)
```

```{r}
table(sel_clust@cluster)
```

### GAK

```{r}
tic()
clust_gak <- tsclust(
  series = tdengue, 
  type = "partitional", 
  k = k_seq,
  distance = "gak",
  seed = 13
)
toc()
```

```{r}
names(clust_gak) <- paste0("k_", k_seq)
res_cvi <- sapply(clust_gak, cvi, type = "internal") %>% 
  t() %>%
  as_tibble(rownames = "k") %>%
  arrange(-Sil)

res_cvi %>%
  gt::gt()
```

```{r}
sel_clust <- clust_gak[[res_cvi[[1,1]]]]

plot(sel_clust)
plot(sel_clust, type = "centroids", lty = 1)
```

```{r}
table(sel_clust@cluster)
```

## Session info

```{r}
sessionInfo()
```
