{
  "hash": "cc63be25f96cb713cbaa0b3f6e711173",
  "result": {
    "markdown": "---\ntitle: \"Missing data analysis\"\nauthor: Raphael Saldanha\ndate: last-modified\n---\n\n\nThis report presents a missing data analysis from the raw parquet files.\n\nConsidering the high number of variables, this report will use a subset of the most relevant ones for this research.\n\n## Packages\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\nlibrary(arrow)\nlibrary(naniar)\nlibrary(knitr)\nlibrary(lubridate)\nsource(\"../functions.R\")\n```\n:::\n\n\n### Execution node\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnode_name()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"rfsaldanha\"\n```\n:::\n:::\n\n\n## Load data\n\n\n::: {.cell}\n\n```{.r .cell-code}\nimportant_vars <- c(\"ID_AGRAVO\", \"DT_NOTIFIC\", \"ID_UNIDADE\",\n                    \"DT_SIN_PRI\", \"CS_SEXO\", \"CS_GESTANT\",\n                    \"CS_RACA\", \"CS_ESCOL_N\", \"ID_MN_RESI\",\n                    \"COUFINF\", \"COMUNINF\", \"ID_OCUPA_N\",\n                    \"DT_SORO\", \"RESUL_SORO\", \"SOROTIPO\", \n                    \"CLASSI_FIN\", \"CRITERIO\", \"EVOLUCAO\",\n                    \"DT_OBITO\", \"HOSPITALIZ\", \"DT_INTERNA\")\n\ndengue <- open_dataset(sources = data_dir(\"dengue_data/parquets\")) %>%\n  select(all_of(important_vars)) %>%\n  collect()\n```\n:::\n\n\n## Overall\n\nConsidering all records.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue %>% \n  miss_var_summary() %>%\n  kable(\n    format.args = list(big.mark = \".\", decimal.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n|variable   |     n_miss|   pct_miss|\n|:----------|----------:|----------:|\n|DT_OBITO   | 42.606.078| 99,8635885|\n|SOROTIPO   | 42.482.960| 99,5750145|\n|DT_INTERNA | 41.524.276| 97,3279730|\n|DT_SORO    | 29.762.226| 69,7591242|\n|COUFINF    | 27.563.344| 64,6052059|\n|COMUNINF   | 25.484.520| 59,7326892|\n|HOSPITALIZ | 20.859.220| 48,8915352|\n|RESUL_SORO | 16.507.868| 38,6924827|\n|EVOLUCAO   | 12.705.373| 29,7798859|\n|CS_ESCOL_N | 12.472.991| 29,2352101|\n|CRITERIO   |  9.437.047| 22,1193178|\n|CS_RACA    |  7.401.103| 17,3473067|\n|CLASSI_FIN |  4.841.110| 11,3469871|\n|CS_GESTANT |  4.610.733| 10,8070107|\n|CS_SEXO    |  4.602.693| 10,7881659|\n|ID_OCUPA_N |  1.538.450|  3,6059441|\n|ID_UNIDADE |      7.362|  0,0172557|\n|ID_MN_RESI |      5.361|  0,0125655|\n|DT_SIN_PRI |        227|  0,0005321|\n|DT_NOTIFIC |          2|  0,0000047|\n|ID_AGRAVO  |          0|  0,0000000|\n:::\n:::\n\n\n### Variables quality\n\n#### Residence municipality: ID_MN_RESI\n\nCheck var length. 6 characters are expected.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue %>%\n  mutate(\n    ID_MN_RESI_check = if_else(nchar(ID_MN_RESI) == 6, \n                               false = FALSE,\n                               true = TRUE)\n  ) %>%\n  group_by(ID_MN_RESI_check) %>%\n  summarise(freq = n()) %>%\n  ungroup() %>%\n  kable(\n    format.args = list(big.mark = \".\", decimal.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n|ID_MN_RESI_check |       freq|\n|:----------------|----------:|\n|FALSE            |          8|\n|TRUE             | 42.658.908|\n|NA               |      5.361|\n:::\n:::\n\n\n42.658.908 records on the database meets the criteria. 8 records have invalid municipalty codes and this information is missing for 5.361 records. Inputation from COMUNINF is a possibility.\n\n#### Final classification of the notification: CLASSI_FIN\n\nIt is expected that the notifications final classification are labeled.\n\n\n::: {.cell}\n\n```{.r .cell-code}\ndengue %>%\n  group_by(CLASSI_FIN) %>%\n  summarise(freq = n()) %>%\n  ungroup() %>%\n  kable(\n    format.args = list(big.mark = \".\", decimal.mark = \",\")\n  )\n```\n\n::: {.cell-output-display}\n|CLASSI_FIN                   |       freq|\n|:----------------------------|----------:|\n|1                            |    616.024|\n|2                            |     15.924|\n|3                            |      5.176|\n|4                            |        182|\n|5                            |    378.316|\n|6                            |          6|\n|8                            |    150.720|\n|Dengue                       | 13.820.647|\n|Dengue clássico              |  5.373.114|\n|Dengue com complicações      |     46.146|\n|Dengue com sinais de alarme  |    203.547|\n|Dengue grave                 |     17.888|\n|Descartado                   | 12.535.942|\n|Febre hemorrágica do dengue  |     14.272|\n|Inconclusivo                 |  4.644.503|\n|Síndrome do choque do dengue |        760|\n|NA                           |  4.841.110|\n:::\n:::\n\n\nSeveral records have invalid labels and 4.841.110 are missing. This missing data may be from two causes: (1) the notification is being evaluated or (2) a real missing.\n\n#### Date of the first symptons onset: DT_SIN_PRI\n\nThis is the date most near to the infection date and more relevant to epidemiological analysis.\n\n\n::: {.cell}\n\n```{.r .cell-code}\nvalid_interval <- interval(ymd(\"2001-01-01\"), ymd(\"2023-12-31\"))\n\ndengue %>%\n  mutate(\n    DT_SIN_PRI_check = ymd(DT_SIN_PRI) %within% valid_interval\n  ) %>%\n  group_by(DT_SIN_PRI_check) %>%\n  summarise(freq = n()) %>%\n  ungroup() %>%\n  kable(\n    format.args = list(big.mark = \".\", decimal.mark = \",\")\n  )\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: There was 1 warning in `mutate()`.\nℹ In argument: `DT_SIN_PRI_check = ymd(DT_SIN_PRI) %within% valid_interval`.\nCaused by warning:\n!  1 failed to parse.\n```\n:::\n\n::: {.cell-output-display}\n|DT_SIN_PRI_check |       freq|\n|:----------------|----------:|\n|FALSE            |     38.197|\n|TRUE             | 42.625.852|\n|NA               |        228|\n:::\n:::\n\n\nThis variable is missing for 228 records. For 38.197 records, we have invalid dates (outside the period 2001-2023). It is possible to imputate with DT_NOTIFIC (date of notification), if valid.\n\n## Session info\n\n\n::: {.cell}\n\n```{.r .cell-code}\nsessionInfo()\n```\n\n::: {.cell-output .cell-output-stdout}\n```\nR version 4.3.2 (2023-10-31)\nPlatform: x86_64-pc-linux-gnu (64-bit)\nRunning under: Ubuntu 22.04.4 LTS\n\nMatrix products: default\nBLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.10.0 \nLAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.10.0\n\nlocale:\n [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              \n [3] LC_TIME=en_CA.UTF-8        LC_COLLATE=en_US.UTF-8    \n [5] LC_MONETARY=en_CA.UTF-8    LC_MESSAGES=en_US.UTF-8   \n [7] LC_PAPER=en_CA.UTF-8       LC_NAME=C                 \n [9] LC_ADDRESS=C               LC_TELEPHONE=C            \n[11] LC_MEASUREMENT=en_CA.UTF-8 LC_IDENTIFICATION=C       \n\ntime zone: Europe/Paris\ntzcode source: system (glibc)\n\nattached base packages:\n[1] stats     graphics  grDevices utils     datasets  methods   base     \n\nother attached packages:\n [1] knitr_1.45      naniar_1.0.0    arrow_14.0.0.2  lubridate_1.9.3\n [5] forcats_1.0.0   stringr_1.5.1   dplyr_1.1.4     purrr_1.0.2    \n [9] readr_2.1.5     tidyr_1.3.1     tibble_3.2.1    ggplot2_3.4.4  \n[13] tidyverse_2.0.0\n\nloaded via a namespace (and not attached):\n [1] bit_4.0.5         gtable_0.3.4      jsonlite_1.8.8    compiler_4.3.2   \n [5] visdat_0.6.0      tidyselect_1.2.0  assertthat_0.2.1  scales_1.3.0     \n [9] yaml_2.3.8        fastmap_1.1.1     R6_2.5.1          generics_0.1.3   \n[13] htmlwidgets_1.6.4 munsell_0.5.0     pillar_1.9.0      tzdb_0.4.0       \n[17] rlang_1.1.3       utf8_1.2.4        stringi_1.8.3     xfun_0.42        \n[21] bit64_4.0.5       timechange_0.3.0  cli_3.6.2         withr_3.0.0      \n[25] magrittr_2.0.3    digest_0.6.34     grid_4.3.2        hms_1.1.3        \n[29] lifecycle_1.0.4   vctrs_0.6.5       evaluate_0.23     glue_1.7.0       \n[33] fansi_1.0.6       colorspace_2.1-0  rmarkdown_2.25    tools_4.3.2      \n[37] pkgconfig_2.0.3   htmltools_0.5.7  \n```\n:::\n:::\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}